import datetime
from sqlalchemy.orm import Session

from app.models.user import User, UserRole
from app.models.case import Case, CaseStatus, CasePriority, LegalCategory
from app.models.audit import AuditLog, AuditAction
from app.services.auth_service import get_password_hash


def seed_database(db: Session):
    """
    Seed 10-20 realistic Bangladesh legal-aid cases, DLAO officers, panel lawyers,
    and audit histories into the authoritative database.
    Idempotent: skips if data is already present.
    """
    def ensure_user(
        email: str,
        password_raw: str,
        full_name: str,
        full_name_bn: str,
        role: UserRole,
        phone_number: str = None,
        district: str = "Dhaka",
        specialization: str = None,
    ) -> User:
        user = db.query(User).filter(User.email == email).first()
        if not user:
            user = User(
                email=email,
                hashed_password=get_password_hash(password_raw),
                full_name=full_name,
                full_name_bn=full_name_bn,
                role=role,
                phone_number=phone_number,
                district=district,
                specialization=specialization,
                is_active=True,
            )
            db.add(user)
            db.commit()
            db.refresh(user)
        return user

    # 1. Standard Judge & Evaluator Accounts
    officer_default = ensure_user(
        email="officer@dlas.gov.bd",
        password_raw="officer123",
        full_name="Mahmudur Rahman, DLAO",
        full_name_bn="মাহমুদুর রহমান (ডিএলএও)",
        role=UserRole.DLAO_OFFICER,
        phone_number="+8801711000000",
        district="Dhaka",
        specialization="District Legal Aid Administration",
    )

    lawyer_default = ensure_user(
        email="lawyer@dlas.gov.bd",
        password_raw="lawyer123",
        full_name="Adv. Nazmul Huda",
        full_name_bn="অ্যাডভোকেট নাজমুল হুদা",
        role=UserRole.PANEL_LAWYER,
        phone_number="+8801811000000",
        district="Dhaka",
        specialization="Land & Property Disputes",
    )

    admin_default = ensure_user(
        email="admin@dlas.gov.bd",
        password_raw="admin123",
        full_name="System Administrator",
        full_name_bn="সিস্টেম অ্যাডমিনিস্ট্রেটর",
        role=UserRole.DLAO_OFFICER,
        phone_number="+8801700000000",
        district="National",
        specialization="Platform Operations & Audit",
    )

    # 2. Regional Legal Officers & Panel Lawyers
    dlao_dhaka = ensure_user(
        email="dlao.dhaka@dlas.gov.bd",
        password_raw="DlaoPass2026!",
        full_name="Mahmudur Rahman, DLAO",
        full_name_bn="মাহমুদুর রহমান (ডিএলএও)",
        role=UserRole.DLAO_OFFICER,
        phone_number="+8801711000001",
        district="Dhaka",
        specialization="Judicial & Legal Aid Administration",
    )

    dlao_ctg = ensure_user(
        email="dlao.ctg@dlas.gov.bd",
        password_raw="DlaoPass2026!",
        full_name="Fatema Zohra, DLAO",
        full_name_bn="ফাতেমা জোহরা (ডিএলএও)",
        role=UserRole.DLAO_OFFICER,
        phone_number="+8801711000002",
        district="Chittagong",
        specialization="Family & Civil Mediation",
    )

    lawyer_land = ensure_user(
        email="lawyer.nazmul@dlas.gov.bd",
        password_raw="LawyerPass2026!",
        full_name="Adv. Nazmul Huda",
        full_name_bn="অ্যাডভোকেট নাজমুল হুদা",
        role=UserRole.PANEL_LAWYER,
        phone_number="+8801811000003",
        district="Dhaka",
        specialization="Land & Property Disputes",
    )

    lawyer_family = ensure_user(
        email="lawyer.farhana@dlas.gov.bd",
        password_raw="LawyerPass2026!",
        full_name="Adv. Farhana Yasmin",
        full_name_bn="অ্যাডভোকেট ফারহানা ইয়াসমিন",
        role=UserRole.PANEL_LAWYER,
        phone_number="+8801811000004",
        district="Chittagong",
        specialization="Family Law & Domestic Violence",
    )

    lawyer_labour = ensure_user(
        email="lawyer.kamrul@dlas.gov.bd",
        password_raw="LawyerPass2026!",
        full_name="Adv. Kamrul Hasan",
        full_name_bn="অ্যাডভোকেট কামরুল হাসান",
        role=UserRole.PANEL_LAWYER,
        phone_number="+8801811000005",
        district="Dhaka",
        specialization="Labour & Industrial Relations",
    )

    lawyer_criminal = ensure_user(
        email="lawyer.tariqul@dlas.gov.bd",
        password_raw="LawyerPass2026!",
        full_name="Adv. Tariqul Islam",
        full_name_bn="অ্যাডভোকেট তরিকুল ইসলাম",
        role=UserRole.PANEL_LAWYER,
        phone_number="+8801811000006",
        district="Rajshahi",
        specialization="Indigent Criminal Defense & Bail",
    )

    system_ai = ensure_user(
        email="ai.system@dlas.internal",
        password_raw="SystemAIPass2026!",
        full_name="DLAS Gemini Intake Engine",
        full_name_bn="ডিএলএএস এআই ইনটেক ইঞ্জিন",
        role=UserRole.SYSTEM_AI,
        phone_number=None,
        district="National",
        specialization="AI Entity Extraction & Triage",
    )

    citizen_user = ensure_user(
        email="citizen.shahnaz@gmail.com",
        password_raw="CitizenPass2026!",
        full_name="Shahnaz Akter",
        full_name_bn="শাহনাজ আক্তার",
        role=UserRole.APPLICANT,
        phone_number="+8801911000007",
        district="Dhaka",
    )

    # 3. Check if Cases already seeded
    if db.query(Case).count() > 0:
        return

    # 2. Seed Fictional Cases
    cases_data = [
        {
            "tracking_id": "DLAS-2026-0001",
            "title": "Maintenance and Child Support under Family Courts Ordinance",
            "title_bn": "পারিবারিক আদালত অধ্যাদেশের অধীনে খোরপোশ ও শিশু ভরণপোষণ দাবি",
            "description": "Applicant Shahnaz Akter was deserted by her spouse 8 months ago without financial support for two minor children. Husband resides in Keraniganj and refuses maintenance.",
            "description_bn": "আবেদনকারী শাহনাজ আক্তারকে ৮ মাস আগে স্বামী কোনো ভরণপোষণ না দিয়ে দুই অপ্রাপ্তবয়স্ক সন্তানসহ ফেলে চলে যান। স্বামী কেরানীগঞ্জে বসবাস করেন এবং খোরপোশ দিতে অস্বীকার করছেন।",
            "legal_category": LegalCategory.FAMILY_MATRIMONIAL,
            "status": CaseStatus.PENDING_HUMAN_REVIEW,
            "priority": CasePriority.HIGH,
            "applicant_name": "Shahnaz Akter",
            "applicant_phone": "+8801911000007",
            "applicant_nid": "19852691234567890",
            "applicant_income_bdt": 8500.0,
            "district": "Dhaka",
            "upazila": "Keraniganj",
            "intake_channel": "PHONE_VOICE",
            "ai_summary": "Intake via voice helpline (16430). Abandonment and maintenance dispute. Applicant monthly income BDT 8,500 qualifies under statutory threshold (<15,000 BDT).",
            "ai_urgency_score": "HIGH",
        },
        {
            "tracking_id": "DLAS-2026-0002",
            "title": "Unlawful Eviction and Homestead Land Dispossession",
            "title_bn": "বসতভিটা থেকে বেআইনি উচ্ছেদ ও বেদখল প্রতিরোধ",
            "description": "Powerful local actors forged Khatian documents attempting to forcibly dispossess applicant Farid Ahmed from 12 decimals of ancestral homestead land in Patiya.",
            "description_bn": "পটিয়া উপজেলায় পৈতৃক ১২ শতক বসতভিটা থেকে ভুয়া খতিয়ান তৈরি করে আবেদনকারী ফরিদ আহমেদকে জোরপূর্বক উচ্ছেদের চেষ্টা চলছে।",
            "legal_category": LegalCategory.LAND_PROPERTY,
            "status": CaseStatus.PANEL_LAWYER_QUEUE,
            "priority": CasePriority.EMERGENCY,
            "applicant_name": "Farid Ahmed",
            "applicant_phone": "+8801712345678",
            "applicant_nid": "1234567890",
            "applicant_income_bdt": 11000.0,
            "district": "Chittagong",
            "upazila": "Patiya",
            "intake_channel": "WEB",
            "ai_summary": "Land demarcation and threat of physical dispossession. Urgent injunctive relief needed.",
            "ai_urgency_score": "EMERGENCY",
            "verification_notes": "Verified by DLAO Chittagong. CS/RS Khatian copies reviewed. Eligible for emergency injunction assistance.",
            "verified_by_id": dlao_ctg.id,
            "verified_at": datetime.datetime.utcnow() - datetime.timedelta(days=1),
        },
        {
            "tracking_id": "DLAS-2026-0003",
            "title": "Wrongful Termination and Unpaid RMG Wages in Ashulia",
            "title_bn": "আশুলিয়ায় পোশাক শ্রমিকের অন্যায় বরখাস্ত ও বকেয়া মজুরি আদায়",
            "description": "Garment worker Md. Rafiqul was terminated without notice or terminal benefits after 4 years of continuous service following factory reorganization.",
            "description_bn": "পোশাক শ্রমিক মো. রফিকুল ৪ বছর চাকরির পর কোনো নোটিশ বা গ্র্যাচুইটি ছাড়াই বেআইনিভাবে কারখানা থেকে ছাঁটাই হয়েছেন।",
            "legal_category": LegalCategory.LABOUR_EMPLOYMENT,
            "status": CaseStatus.LAWYER_REVIEW,
            "priority": CasePriority.MEDIUM,
            "applicant_name": "Md. Rafiqul Islam",
            "applicant_phone": "+8801822334455",
            "applicant_nid": "5566778899",
            "applicant_income_bdt": 12500.0,
            "district": "Dhaka",
            "upazila": "Savar",
            "intake_channel": "WALK_IN",
            "ai_summary": "Labour Act 2006 Section 26/27 claim. 4 months severance pay and earned leave encashment pending.",
            "verification_notes": "Employment ID card and pay slips verified. Dispatched to Labour Panel Lawyer.",
            "verified_by_id": dlao_dhaka.id,
            "verified_at": datetime.datetime.utcnow() - datetime.timedelta(days=3),
            "assigned_lawyer_id": lawyer_labour.id,
            "assigned_at": datetime.datetime.utcnow() - datetime.timedelta(days=2),
        },
        {
            "tracking_id": "DLAS-2026-0004",
            "title": "Dowry Harassment and Domestic Violence Injunction",
            "title_bn": "যৌতুক দাবি ও পারিবারিক নির্যাতন প্রতিরোধে নিষেধাজ্ঞা আবেদন",
            "description": "Rokeya Begum subjected to physical assault and demands for BDT 200,000 dowry. Seeking immediate protection order under Domestic Violence Act 2010.",
            "description_bn": "রোকেয়া বেগম ২ লাখ টাকা যৌতুকের দাবিতে শারীরিক নির্যাতনের শিকার। পারিবারিক সহিংসতা প্রতিরোধ আইন ২০১০ এর অধীনে জরুরি সুরক্ষা আদেশ প্রয়োজন।",
            "legal_category": LegalCategory.DOMESTIC_VIOLENCE_DOWRY,
            "status": CaseStatus.PANEL_LAWYER_QUEUE,
            "priority": CasePriority.EMERGENCY,
            "applicant_name": "Rokeya Begum",
            "applicant_phone": "+8801733445566",
            "applicant_nid": "9876543210",
            "applicant_income_bdt": 4000.0,
            "district": "Sylhet",
            "upazila": "Beanibazar",
            "intake_channel": "PHONE_VOICE",
            "ai_summary": "Severe physical domestic violence and extortionate dowry demand. Immediate safety risk.",
            "verification_notes": "Medical certificate from Upazila Health Complex verified. Approved for expedited panel advocate representation.",
            "verified_by_id": dlao_dhaka.id,
            "verified_at": datetime.datetime.utcnow() - datetime.timedelta(hours=5),
        },
        {
            "tracking_id": "DLAS-2026-0005",
            "title": "Partition Suit for Ancestral Agricultural Land",
            "title_bn": "পৈতৃক কৃষিজমির বাটোয়ারা মোকদ্দমা",
            "description": "Applicant Abdul Kader denied equitable share of 2.5 acres of farmland by elder brothers in Paba Upazila.",
            "description_bn": "পবা উপজেলায় পৈতৃক আড়াই একর কৃষিজমিতে ন্যায্য হিস্যা থেকে বঞ্চিত হচ্ছেন আবেদনকারী আব্দুল কাদের।",
            "legal_category": LegalCategory.LAND_PROPERTY,
            "status": CaseStatus.PENDING_HUMAN_REVIEW,
            "priority": CasePriority.MEDIUM,
            "applicant_name": "Abdul Kader",
            "applicant_phone": "+8801555667788",
            "applicant_nid": "1122334455",
            "applicant_income_bdt": 9000.0,
            "district": "Rajshahi",
            "upazila": "Paba",
            "intake_channel": "WEB",
            "ai_summary": "Partition suit eligibility. Mutation records and death certificate of father submitted.",
        },
        {
            "tracking_id": "DLAS-2026-0006",
            "title": "Indigent Widow Social Welfare & Maintenance Rights",
            "title_bn": "দুস্থ বিধবার সামাজিক নিরাপত্তা ও পারিবারিক অধিকার সুরক্ষা",
            "description": "Destitute elderly widow evicted from husband's home by in-laws after husband's demise. No source of independent income.",
            "description_bn": "স্বামীর মৃত্যুর পর শ্বশুরবাড়ির লোকজন কর্তৃক ভিটা থেকে বিতাড়িত নিঃস্ব বয়স্ক বিধবা। আয়ের কোনো উৎস নেই।",
            "legal_category": LegalCategory.FAMILY_MATRIMONIAL,
            "status": CaseStatus.PENDING_HUMAN_REVIEW,
            "priority": CasePriority.HIGH,
            "applicant_name": "Momena Khatun",
            "applicant_phone": "+8801766778899",
            "applicant_nid": "2233445566",
            "applicant_income_bdt": 2000.0,
            "district": "Rangpur",
            "upazila": "Kurigram Sadar",
            "intake_channel": "PHONE_VOICE",
            "ai_summary": "Destitute widow status verified via Union Parishad chairman certificate.",
        },
        {
            "tracking_id": "DLAS-2026-0007",
            "title": "Breach of Agricultural Tenancy and Crop Confiscation",
            "title_bn": "বর্গাচাষ চুক্তি লঙ্ঘন ও ফসল জোরপূর্বক জবরদখল",
            "description": "Tenant farmer Monirul Haque's share-cropped boro paddy unlawfully harvested and seized by local landlord in Bagerhat.",
            "description_bn": "বাগেরহাটে বর্গাচাষী মনিরুল হকের বোরো ধান জোতদার কর্তৃক জোরপূর্বক কেটে নেওয়া হয়েছে।",
            "legal_category": LegalCategory.CIVIL_GENERAL,
            "status": CaseStatus.NEEDS_INFORMATION,
            "priority": CasePriority.MEDIUM,
            "applicant_name": "Monirul Haque",
            "applicant_phone": "+8801677889900",
            "applicant_nid": "3344556677",
            "applicant_income_bdt": 10500.0,
            "district": "Khulna",
            "upazila": "Bagerhat Sadar",
            "intake_channel": "WEB",
            "verification_notes": "Additional Information Needed: Please provide local Union Parishad land tenancy receipt or witness testimony.",
        },
        {
            "tracking_id": "DLAS-2026-0008",
            "title": "Domestic Abuse Injunction and Child Custody",
            "title_bn": "পারিবারিক নির্যাতন থেকে সুরক্ষা ও শিশুর জিম্মা",
            "description": "Shanta Halder seeking interim custody of 4-year-old daughter taken forcibly by abusive former partner.",
            "description_bn": "প্রাক্তন স্বামীর নিকট থেকে ৪ বছরের কন্যা সন্তান উদ্ধার ও সুরক্ষার জন্য আদালতের আদেশ প্রার্থনা।",
            "legal_category": LegalCategory.DOMESTIC_VIOLENCE_DOWRY,
            "status": CaseStatus.LAWYER_REVIEW,
            "priority": CasePriority.HIGH,
            "applicant_name": "Shanta Halder",
            "applicant_phone": "+8801988990011",
            "applicant_nid": "4455667788",
            "applicant_income_bdt": 6000.0,
            "district": "Barishal",
            "upazila": "Jhalakathi Sadar",
            "intake_channel": "PHONE_VOICE",
            "verification_notes": "Approved for emergency Guardianship Act petition.",
            "verified_by_id": dlao_ctg.id,
            "verified_at": datetime.datetime.utcnow() - datetime.timedelta(days=4),
            "assigned_lawyer_id": lawyer_family.id,
            "assigned_at": datetime.datetime.utcnow() - datetime.timedelta(days=3),
        },
        {
            "tracking_id": "DLAS-2026-0009",
            "title": "Under-Trial Indigent Defense and Bail Application",
            "title_bn": "অসচ্ছল বিচারাধীন আসামির পক্ষে জামিন আবেদন ও আইনি প্রতিরক্ষা",
            "description": "Day-laborer arrested under bailable section; family cannot afford private advocate fees for Sessions Court bail petition.",
            "description_bn": "জামিনযোগ্য ধারায় গ্রেপ্তারকৃত দিনমজুরের পরিবার আইনজীবী নিয়োগে অপারগ। জজ কোর্টে জামিন শুনানি প্রয়োজন।",
            "legal_category": LegalCategory.CRIMINAL_DEFENSE_BAIL,
            "status": CaseStatus.LAWYER_REVIEW,
            "priority": CasePriority.HIGH,
            "applicant_name": "Nurul Islam",
            "applicant_phone": "+8801799001122",
            "applicant_nid": "5566778899",
            "applicant_income_bdt": 7500.0,
            "district": "Mymensingh",
            "upazila": "Trishal",
            "intake_channel": "WALK_IN",
            "verification_notes": "Statutory eligibility verified under Legal Aid Services Act indigent prisoner clause.",
            "verified_by_id": dlao_dhaka.id,
            "verified_at": datetime.datetime.utcnow() - datetime.timedelta(days=2),
            "assigned_lawyer_id": lawyer_criminal.id,
            "assigned_at": datetime.datetime.utcnow() - datetime.timedelta(days=1),
        },
        {
            "tracking_id": "DLAS-2026-0010",
            "title": "Industrial Workplace Injury and Disablement Compensation",
            "title_bn": "কর্মক্ষেত্রে দুর্ঘটনায় অঙ্গহানি ও ক্ষতিপূরণ দাবি",
            "description": "Spinning mill operator lost two fingers in unprotected machine gear. Employer refuses statutory compensation under Labour Act.",
            "description_bn": "স্পিনিং মিলে অরক্ষিত মেশিনে আঙুল হারিয়ে কর্মক্ষমতা হারানো শ্রমিকের ক্ষতিপূরণ আবেদন।",
            "legal_category": LegalCategory.LABOUR_EMPLOYMENT,
            "status": CaseStatus.PENDING_HUMAN_REVIEW,
            "priority": CasePriority.HIGH,
            "applicant_name": "Beauty Rani",
            "applicant_phone": "+8801833445566",
            "applicant_nid": "6677889900",
            "applicant_income_bdt": 11500.0,
            "district": "Dhaka",
            "upazila": "Gazipur Sadar",
            "intake_channel": "WEB",
            "ai_summary": "Workplace injury compensation claim under Section 150 of Labour Act 2006. Medical discharge paper attached.",
        },
        {
            "tracking_id": "DLAS-2026-0011",
            "title": "Succession Certificate and Bank Account Release",
            "title_bn": "উত্তরাধিকার সনদ ও মরহুমের ব্যাংক হিসাব অবমুক্তকরণ",
            "description": "Deceased breadwinner left small savings deposit; heirs require legal aid to file Succession Act petition in District Judge Court.",
            "description_bn": "মরহুমের ক্ষুদ্র সঞ্চয় উত্তোলনে ওয়ারিশদের সাকসেশন সার্টিফিকেট প্রাপ্তিতে আইনি সহায়তা।",
            "legal_category": LegalCategory.CIVIL_GENERAL,
            "status": CaseStatus.NEW,
            "priority": CasePriority.LOW,
            "applicant_name": "Faruk Hossain",
            "applicant_phone": "+8801944556677",
            "applicant_nid": "7788990011",
            "applicant_income_bdt": 13000.0,
            "district": "Chittagong",
            "upazila": "Comilla Sadar",
            "intake_channel": "WEB",
        },
        {
            "tracking_id": "DLAS-2026-0012",
            "title": "Abandoned Mother Seeking Immediate Child Subsistence",
            "title_bn": "স্বামী পরিত্যক্ত মায়ের জরুরি শিশু ভরণপোষণ",
            "description": "Deserted with infant in coastal area without shelter or food support. Emergency relief and family court petition required.",
            "description_bn": "উপকূলীয় অঞ্চলে শিশু সন্তানসহ স্বামী কর্তৃক পরিত্যক্ত নারীর জন্য জরুরি সহায়তা ও আইনি পদক্ষেপ।",
            "legal_category": LegalCategory.FAMILY_MATRIMONIAL,
            "status": CaseStatus.PANEL_LAWYER_QUEUE,
            "priority": CasePriority.EMERGENCY,
            "applicant_name": "Jaheda Khatun",
            "applicant_phone": "+8801755667788",
            "applicant_nid": "8899001122",
            "applicant_income_bdt": 3500.0,
            "district": "Chittagong",
            "upazila": "Cox's Bazar Sadar",
            "intake_channel": "PHONE_VOICE",
            "ai_summary": "Extreme destitution and immediate hunger vulnerability.",
            "verification_notes": "Verified by DLAO Chittagong. Forwarded to Panel Lawyer queue with top urgency.",
            "verified_by_id": dlao_ctg.id,
            "verified_at": datetime.datetime.utcnow() - datetime.timedelta(hours=2),
        },
        {
            "tracking_id": "DLAS-2026-0013",
            "title": "Agricultural Land Demarcation and Boundary Wall Encroachment",
            "title_bn": "কৃষিজমির সীমানা নির্ধারণ ও সীমানা প্রাচীর জবরদখল",
            "description": "Applicant Joynal Abedin's agricultural plot boundary pillars shifted overnight by neighboring influential brickfield owner in Dinajpur.",
            "description_bn": "দিনাজপুরে ইটভাটা মালিক কর্তৃক আবেদনকারী জয়নাল আবেদীনের ফসলি জমির সীমানা পিলার উপড়ে জবরদখল।",
            "legal_category": LegalCategory.LAND_PROPERTY,
            "status": CaseStatus.NEW,
            "priority": CasePriority.MEDIUM,
            "applicant_name": "Joynal Abedin",
            "applicant_phone": "+8801711223344",
            "applicant_nid": "9900112233",
            "applicant_income_bdt": 9500.0,
            "district": "Rangpur",
            "upazila": "Dinajpur Sadar",
            "intake_channel": "WEB",
        },
        {
            "tracking_id": "DLAS-2026-0014",
            "title": "Recovery of Dower (Moharana) and Maintenance Following Abandonment",
            "title_bn": "দেনমোহর ও দাম্পত্য অধিকার পুনরুদ্ধার মোকদ্দমা",
            "description": "Shilpi Begum deserted after 7 years of marriage. Husband remarried without statutory arbitration council permission under Muslim Family Laws Ordinance 1961.",
            "description_bn": "মুসলিম পারিবারিক আইন অধ্যাদেশ ১৯৬১ লঙ্ঘন করে অনুমতিহীন দ্বিতীয় বিয়ে এবং প্রথম স্ত্রীর দেনমোহর ও ভরণপোষণ অস্বীকার।",
            "legal_category": LegalCategory.FAMILY_MATRIMONIAL,
            "status": CaseStatus.PENDING_HUMAN_REVIEW,
            "priority": CasePriority.HIGH,
            "applicant_name": "Shilpi Begum",
            "applicant_phone": "+8801811334455",
            "applicant_nid": "1011121314",
            "applicant_income_bdt": 5000.0,
            "district": "Dhaka",
            "upazila": "Narayanganj Sadar",
            "intake_channel": "PHONE_VOICE",
            "ai_summary": "Muslim Family Laws Ordinance 1961 Section 6 violation and unpaid dower of BDT 150,000.",
            "ai_urgency_score": "HIGH",
        },
        {
            "tracking_id": "DLAS-2026-0015",
            "title": "Money Recovery Suit for Small Weaver Cottage Cooperative",
            "title_bn": "ক্ষুদ্র তাঁতি সমবায়ের পণ্য সরবরাহের পাওনা টাকা আদায়",
            "description": "Local handloom cooperative supplied traditional lungi/gamcha worth BDT 45,000 to merchant who defaulted on payment.",
            "description_bn": "স্থানীয় ক্ষুদ্র তাঁতিদের ৪৫,০০০ টাকার লুঙ্গি ও গামছা সরবরাহ বাবদ পাওনা টাকা আত্মসাতের বিরুদ্ধে মানি স্যুট।",
            "legal_category": LegalCategory.CIVIL_GENERAL,
            "status": CaseStatus.VERIFIED,
            "priority": CasePriority.LOW,
            "applicant_name": "Tarek Mahmud",
            "applicant_phone": "+8801911445566",
            "applicant_nid": "1516171819",
            "applicant_income_bdt": 12000.0,
            "district": "Rajshahi",
            "upazila": "Bogra Sadar",
            "intake_channel": "WALK_IN",
            "verification_notes": "Supply receipts and delivery challans verified. Eligible for civil legal aid representation.",
            "verified_by_id": dlao_dhaka.id,
            "verified_at": datetime.datetime.utcnow() - datetime.timedelta(days=1),
        },
        {
            "tracking_id": "DLAS-2026-0016",
            "title": "Urgent Domestic Violence Protection Order for Abandoned Wife",
            "title_bn": "নির্যাতিতা নারীর জন্য জরুরি পারিবারিক সহিংসতা সুরক্ষা আদেশ",
            "description": "Applicant subjected to repeated physical abuse and death threats over dowry demands. Requires immediate court injunction.",
            "description_bn": "যৌতুকের জন্য শারীরিক নির্যাতন ও প্রাণনাশের হুমকি। পারিবারিক সহিংসতা প্রতিরোধ ও সুরক্ষা আইনের অধীনে জরুরি আদেশ প্রার্থনা।",
            "legal_category": LegalCategory.DOMESTIC_VIOLENCE_DOWRY,
            "status": CaseStatus.PENDING_HUMAN_REVIEW,
            "priority": CasePriority.EMERGENCY,
            "applicant_name": "রাশিদা বেগম",
            "applicant_phone": "+8801722334455",
            "applicant_nid": "1617181920",
            "applicant_income_bdt": 5000.0,
            "district": "Dhaka",
            "upazila": "Savar",
            "intake_channel": "PHONE_VOICE",
            "ai_urgency_score": "URGENT_REVIEW",
            "ai_summary": "High risk of physical harm. Immediate human verification recommended.",
        },
        {
            "tracking_id": "DLAS-2026-0017",
            "title": "Brick Kiln Hazardous Labour Exploitation and Wage Withholding",
            "title_bn": "ইটভাটায় ঝুঁকিপূর্ণ শিশু শ্রম ও শ্রমিকদের বকেয়া মজুরি আদায়",
            "description": "Seasonal kiln workers and minors forced into bonded conditions without payment of agreed BDT 65,000 seasonal wage.",
            "description_bn": "ইটভাটা মালিক কর্তৃক অগ্রিম দাদন ছুতোয় শ্রমিকদের আটকে রেখে মজুরি না দেওয়ার বিরুদ্ধে আইনগত পদক্ষেপ।",
            "legal_category": LegalCategory.LABOUR_EMPLOYMENT,
            "status": CaseStatus.PENDING_HUMAN_REVIEW,
            "priority": CasePriority.HIGH,
            "applicant_name": "মোস্তফা কামাল",
            "applicant_phone": "+8801833445566",
            "applicant_nid": "1718192021",
            "applicant_income_bdt": 8500.0,
            "district": "Barishal",
            "upazila": "Babuganj",
            "intake_channel": "WEB",
        },
        {
            "tracking_id": "DLAS-2026-0018",
            "title": "Char Land Khas Settlement Forcible Eviction Dispute",
            "title_bn": "চরাঞ্চলের খাস জমি বন্দোবস্ত ও অবৈধ উচ্ছেদ প্রতিরোধ",
            "description": "Landless river erosion victims facing violent eviction by influential land grabbers despite government khas allotment.",
            "description_bn": "নদীভাঙন কবলিত ভূমিহীন পরিবারের অনুকূলে সরকারি বন্দোবস্তকৃত খাসজমি থেকে উচ্ছেদ চেষ্টার বিরুদ্ধে প্রতিকার।",
            "legal_category": LegalCategory.LAND_PROPERTY,
            "status": CaseStatus.PENDING_HUMAN_REVIEW,
            "priority": CasePriority.MEDIUM,
            "applicant_name": "আব্দুল জলিল",
            "applicant_phone": "+8801944556677",
            "applicant_nid": "1819202122",
            "applicant_income_bdt": 7000.0,
            "district": "Kurigram",
            "upazila": "Rajarhat",
            "intake_channel": "WALK_IN",
        },
        {
            "tracking_id": "DLAS-2026-0019",
            "title": "Extortion and Intimidation by Estranged In-laws",
            "title_bn": "যৌতুকের মিথ্যা দাবিতে চাঁদাবাজি ও সামাজিক হয়রানি",
            "description": "Demands for extortion money accompanied by threats to kidnap applicant's minor child.",
            "description_bn": "নাবালক সন্তান অপহরণের হুমকি ও অন্যায় অর্থ দাবির বিরুদ্ধে লিগ্যাল এইড সহায়তায় আইনি ব্যবস্থা।",
            "legal_category": LegalCategory.DOMESTIC_VIOLENCE_DOWRY,
            "status": CaseStatus.AI_INTAKE,
            "priority": CasePriority.HIGH,
            "applicant_name": "সাবিনা ইয়াসমিন",
            "applicant_phone": "+8801755667788",
            "applicant_nid": "1920212223",
            "applicant_income_bdt": 6000.0,
            "district": "Khulna",
            "upazila": "Rupsha",
            "intake_channel": "PHONE_VOICE",
        },
        {
            "tracking_id": "DLAS-2026-0020",
            "title": "Indigent Worker Pre-Trial Legal Aid and Bail Defense",
            "title_bn": "দরিদ্র দিনমজুরের কারামুক্তির জন্য সরকারি খরচে জামিন আবেদন",
            "description": "Day laborer wrongly detained in suspicious circumstances case unable to afford private attorney fees.",
            "description_bn": "সন্দেহভাজন হিসেবে গ্রেফতারকৃত দরিদ্র দিনমজুরের পক্ষে সরকারি খরচে আইনজীবী নিয়োগ ও জামিন মোকদ্দমা।",
            "legal_category": LegalCategory.CRIMINAL_DEFENSE_BAIL,
            "status": CaseStatus.PENDING_HUMAN_REVIEW,
            "priority": CasePriority.HIGH,
            "applicant_name": "রফিকুল ইসলাম",
            "applicant_phone": "+8801666778899",
            "applicant_nid": "2021222324",
            "applicant_income_bdt": 9000.0,
            "district": "Sylhet",
            "upazila": "Golapganj",
            "intake_channel": "WEB",
        },
    ]

    for item in cases_data:
        case = Case(
            tracking_id=item["tracking_id"],
            title=item["title"],
            title_bn=item["title_bn"],
            description=item["description"],
            description_bn=item["description_bn"],
            legal_category=item["legal_category"],
            status=item["status"],
            priority=item["priority"],
            applicant_name=item["applicant_name"],
            applicant_phone=item["applicant_phone"],
            applicant_nid=item.get("applicant_nid"),
            applicant_nid_verified=True,
            applicant_income_bdt=item.get("applicant_income_bdt"),
            district=item["district"],
            upazila=item.get("upazila"),
            intake_channel=item.get("intake_channel", "WEB"),
            ai_summary=item.get("ai_summary"),
            ai_urgency_score=item.get("ai_urgency_score"),
            verification_notes=item.get("verification_notes"),
            verified_by_id=item.get("verified_by_id"),
            verified_at=item.get("verified_at"),
            assigned_lawyer_id=item.get("assigned_lawyer_id"),
            assigned_at=item.get("assigned_at"),
            archived=False,
            version=1,
            created_at=datetime.datetime.utcnow() - datetime.timedelta(days=5),
            updated_at=datetime.datetime.utcnow() - datetime.timedelta(days=1),
        )
        db.add(case)
        db.commit()
        db.refresh(case)

        # Create audit entry for seed case
        audit = AuditLog(
            case_id=case.id,
            actor_id=dlao_dhaka.id if case.verified_by_id else None,
            actor_name="System Seed Engine",
            actor_role="system",
            action=AuditAction.CASE_CREATED,
            previous_state=None,
            new_state=case.status,
            notes=f"Seeded demo Bangladesh legal-aid record ({case.tracking_id})",
            timestamp=datetime.datetime.utcnow() - datetime.timedelta(days=5),
        )
        db.add(audit)
        db.commit()
